Hqq deployment
mobiusml/aana_sdk pull request #169
Opened 2024-09-03 08:23 UTC by HRashidi

In this PR we are adding a new deployment for loading HQQ models or quantize a model from its weight.

Key changes:
- Adding hqq deployment
- Adding possibility to load pre-quantized model as well as quantize a model on the fly.
- Adding tests gor hqq deployment

2024-09-09 14:15 UTC, movchan74 requested changes

2024-09-09 14:15 UTC, movchan74 commented on docs/pages/model_hub/hqq.md
> +# Half-Quadratic Quantization Models
Since it only supports text generation, it should be in text_generation.md.

2024-09-09 14:15 UTC, movchan74 commented on docs/pages/model_hub/hqq.md
> +As an example, let's see how to configure the Hugging Face pipeline deployment to quantize [https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct](https://huggingface.co/Salesforce/blip2-opt-2
The link is wrong.

2024-09-09 14:15 UTC, movchan74 commented on docs/pages/model_hub/hqq.md
> +As an example, let's see how to configure the Hugging Face pipeline deployment to quantize [https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct](https://huggingface.co/Salesforce/blip2-opt-2
And it says `Hugging Face pipeline deployment`.

2024-09-09 14:15 UTC, movchan74 commented on docs/pages/model_hub/hqq.md
> +[Half-Quadratic Quantization deployment](./../../reference/deployments.md#aana.deployments.HQQDeployment) allows you to serve *almost* any model from the [Hugging Face Hub](https://huggingface.co/mod
There should be more info about what HQQ is. It should be clearly stated that deployment supports on-fly quantization of text generation (?) models or already quantized models from HF hub with the link to the hf profile of our company. For example, Hicham created colections like this: https://huggingface.co/collections/mobiuslabsgmbh/llama3-hqq-6604257a96fc8b9c4e13e0fe. Maybe we can add a collection called HQQ Quantized LLMs to list all the model supported by this deployment.

2024-09-09 14:15 UTC, movchan74 commented on docs/pages/model_hub/hqq.md
> +!!! example "Meta-Llama-3.1-8B-Instruct"
We need at least one more example with already quantized model.

2024-09-09 14:15 UTC, movchan74 commented on docs/pages/model_hub/hqq.md
> +            backend=HQQBackend.BITBLAS,
Can we add more info on supported backends?

2024-09-09 14:15 UTC, movchan74 commented on pyproject.toml
> +hqq = "0.2.1"
Any reason to pin a specific version?

2024-09-09 14:15 UTC, movchan74 commented on docs/pages/model_hub/hqq.md
> +    from aana.deployments.hqq_deployment import HQQConfig, HQQDeployment
HQQBackend import is missing

2024-09-09 14:15 UTC, movchan74 commented on aana/deployments/hqq_deployment.py
> +    backend: HQQBackend
What is default backend?

2024-09-16 11:02 UTC, movchan74 commented
The PR is ready to be reviewed. But there are still a couple of issues that need to be addressed.
- There is a bug with the compile hack in the HQQ library. The hack is not working when `max_new_tokens` is set to 1024. The same code works fine with `max_new_tokens=512`. The issue is reproducible with the following code: https://gist.github.com/movchan74/07e884d571319ab6881a3ac688e98a14
- HQQ library requires a specific import order for BitBLAS backend to work. But in Aana SDK it's difficult to control the import order. I added a workaround:  importing BitBLAS before anything else in Aana SDK. But it's not a good solution. We need to find out why the import order is important and fix it in the HQQ library.

2024-09-24 14:16 UTC, mobicham reviewed
Looks good! The only comment I have is to make sure the device is not cuda or auto when the model is loaded before being quantized

2024-09-24 15:16 UTC, movchan74 commented on aana/deployments/hqq_text_generation_deployment.py
> +            self.model_kwargs["device_map"] = self.device
So we should set `self.model_kwargs["device_map"] = "cpu"`? I've tested it on meta-llama/Meta-Llama-3.1-8B-Instruct. Shall I test it with 70b?

2024-09-26 14:00 UTC, movchan74 commented on aana/deployments/hqq_text_generation_deployment.py
> +            self.model_kwargs["device_map"] = self.device
I've changed it to `self.model_kwargs["device_map"] = "cpu"`.

2024-09-26 15:15 UTC, mobicham approved these changes

2024-09-27 11:58 UTC, movchan74 approved these changes

2024-09-28 11:02 UTC, mobicham approved these changes

2024-09-28 16:02 UTC, merged